### ISSUE TITLE
Unify Session Storage for all Tabs

### ISSUE THREAD

**Issue by ModisR** [ratdoux/easyreading#4]
Currently, changing the bionic preferences only applies them to the active tab. After switching to a new tab, it must either be refreshed or the inputs played around with some more. We have 2 ways to proceed:

1) Tell the Chrome API to refresh the page or reapply changes after switching to a new tab.
2) Maintain a separate set of bionic preferences for each tab. I like this one the most as a user might want to have multiple tabs with vastly different colour schemes open.

**Comment by ModisR** [comment]
Just realised that following the logic in 2 means that preferences should be scoped not to tabs but to web domains anyway (assuming their styling is consistent for all page) which would require implementing 1 as a first step anyway. Might split off another issue to reflect these two stages.

**Comment by ratdoux** [comment]
I'm currently trying to figure out how to implement blacklisting, and could probably use that same logic for scoping. 
But I don't think we should automatically apply preferences for every domain, and only apply with explicit user input.
Otherwise we'd end up with a fairly long JSON for every domain in local or cloud store (currently using chrome.sync so its cloud) after just a few days of browsing.

**Comment by ModisR** [comment]
Ah, so you reckon the blacklist ticket is directly dependent on this one?

Also, good shout on the storage consideration. We'll just limit the scope of this ticket to step 1 and consider that enough to close it.

**Comment by ratdoux** [comment]
Currently working on saving per domain settings locally, since we only have about 8kb of storage on the cloud and a lot more locally

**Comment by ratdoux** [comment]
https://github.com/ratdoux/easyreading/commit/67bea1c8e0f76fb0771da110057c0c031e32387a

added per domain local storage, have introduced a bug though
